### ISSUE TITLE
Will the user manually commit/push the twiddled file to GitHub?

### ISSUE THREAD

**Issue by kwurst** [StoneyJackson/scramblewords.py#1]
Will `twiddle.py` be run entirely on the local machine, and then the user creates a repository, commits, and pushed the twiddled file?

I think this makes the most sense, but I'm asking because I thinking of how this interfaces with `report.py`. I guess the repository will already exist with the twiddled file in it when `report.py` is run to insert all the incidents into the issue tracker.

**Comment by StoneyJackson** [comment]
Yes. To most flexibly support different use cases, we should let the user decide what and when to check-in, push, add issues, etc. So I'm imagining some workflow like this (probably should go in the readme)

```
## clone the repo with the file to twiddle
$ git clone git://repo.git
$ cd repo

## run twiddle on the file
$ python path-to/twiddle.py .2 the-file.txt

## replace original file with twiddled version
$ mv the-file.txt.TWIDDLED the-file.txt

## commit and publish twiddled version
$ git add the-file.txt
$ git commit -m 'twiddled the-file.txt'
$ git push

## publish issues with report.py
$ python path-to/report.py the-file.INCIDENTS git://repo.git     # making up interface here
```
