### ISSUE TITLE
report.py

### ISSUE THREAD

**Issue by kwurst** [StoneyJackson/scramblewords.py#2]
So, here is how I am thinking that `report.py` will work:

python report.py *namespace/repositoryname* *github-username* *incident-file*

The program will ask for the password interactively with no echo.

Comments? Other command line parameters?

**Comment by StoneyJackson** [comment]
Sounds reasonable. If you want to try to eliminate the first two parameters, you might look to hub for ideas: https://github.com/github/hub

It might be tough though.
