### ISSUE TITLE
Add "Ignore" suggestion

### ISSUE THREAD

**Issue by StoneyJackson** [StoneyJackson/scramblewords.py#6]
Users may want to "Ignore" the repository on GitHub before running report.py. Ignoring will prevent the user from receiving a deluge of email notifications.

Also, when running the activity, the instructor may want to advise students to "Ignore" the repository. Or at least, not watch the entire repository. That way they only receive notifications about issues that they are involved with.

Notes to this this effect should be added to README.

**Comment by kwurst** [comment]
You got flooded, huh?

**Comment by StoneyJackson** [comment]
Yup :)

I had to quickly get to the repo and unsubscribe, then delete the 200+
emails :)

-- 
Stoney Jackson
Sent with Airmail

On February 15, 2017 at 11:48:05 AM, Karl R. Wurst (notifications@github.com)
wrote:

You got flooded, huh?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/StoneyJackson/git-twiddler/issues/6#issuecomment-280066297>,
or mute the thread

**Comment by StoneyJackson** [comment]
Closing since the related reporter functionality will soon be removed from this project.
